version: '3.1'

services:
  frontend:
    image: node:16
    restart: always
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/usr/app
    user: node
    working_dir: /usr/app
    command: bash
    tty: true
    stdin_open: true
    depends_on:
      - api

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306

  api:
    image: node:16
    restart: always
    container_name: api
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/app
    user: node
    working_dir: /usr/app
    command: bash
    # As duas opções abaixo correspondem ao -it
    tty: true # -t
    stdin_open: true #-i 
    depends_on:
      - mysql
